### PR TITLE
add built documentation ZIP file artifact upload to docs workflow

### LINKED ISSUE #281: Upload built documentation as artifact
@mrakitin suggests:

> ... useful to upload artifacts with the built docs, so that the rendering can be checked w/o running the build locally. [[see this example](https://github.com/NSLS-II/sirepo-bluesky/blob/39a7d09a3816f01396a4309149c0c2732606546a/.github/workflows/docs.yml#L96-L99)]

```yaml
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPOSITORY_NAME }}-docs
          path: docs/build/html/
```

### PR DESCRIPTION
**Pull request by prjemian**
- close #281

### CODE REVIEW

**Comment by prjemian** [comment]
GHA suggests:

> [docs (3.9)](https://github.com/bluesky/hklpy/actions/runs/6733954290/job/18303761130#step:7:16)
This action is deprecated and no longer maintained. Please use mamba-org/setup-micromamba instead. See `https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba` for a migration guide.

**Comment by prjemian** [comment]
@mrakitin Ready for review.

**Comment by prjemian** [comment]
Great idea!  This works easily.  [NeXus](https://github.com/nexusformat/definitions/issues/1320) will benefit, too.

**Review by mrakitin — APPROVED** [review]
Looks great! It's now easy to check the docs.

The only issue with the workflow can be that it may not pull enough commits/tags to version the docs properly. We can probably set those to non-default values (from https://github.com/actions/checkout):
```
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''

    # Whether to fetch tags, even if fetch-depth > 0.
    # Default: false
    fetch-tags: ''
```

**Comment by prjemian** [comment]
Solves the problem with the wrong version posted in the web documentation!  Thanks!

**Pull request merged**
