### PR TITLE
add diffractometer get_axis_constraints() method

### LINKED ISSUE #302: add a `get_constraints(axis)` function
Add a `get_constraints(axis)` function to show the constraints for a single axis.  One line, not a table.

Requested by @strempfer

### PR DESCRIPTION
**Pull request by prjemian**
- close #302

### CODE REVIEW

**Comment by prjemian** [comment]
@strempfer @mrakitin This very short PR is ready for review.

**Review by strempfer — APPROVED** [review]
Works great! Thanks!

**Comment by prjemian** [comment]
Need to move the changes from [e6e1d3b](https://github.com/bluesky/hklpy/pull/304/commits/e6e1d3bf7cdf44c5b057c649b58278707a25aba7) to a new branch

**Review by mrakitin — APPROVED** [review]
Looks straightforward!

**Comment by prjemian** [comment]
@strempfer @mrakitin Thanks for the reviews!

**Pull request merged**
