### PR TITLE
add Python 3.9 to unit test suite

### LINKED ISSUE #113: expand test suite to py3.9
add Python 3.9 CI test workflow

### PR DESCRIPTION
**Pull request by prjemian**
FIX #113

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin : Good suggestion!  Ready for review.

**Review by mrakitin — APPROVED** [review]
Looks good, thanks @prjemian! Do we still want to keep Python 3.6 tests?

**Comment by prjemian** [comment]
Let's keep 3.6 a little while longer. Thanks for reviewing.

**Comment by prjemian** [comment]
FYI, 3.6 security fixes [supported through 2021](https://www.python.org/downloads/release/python-360/).  We can afford to be conservative about dropping older Python versions.  Here's the quote from Python.org:

>  Following the release of 3.6.8, we plan to provide security fixes for Python 3.6 as needed through 2021, five years following its initial release.

**Comment by mrakitin** [comment]
Sounds good, I agree with the plan.

**Pull request merged**
