### PR TITLE
restore reflections to the proper sample

### LINKED ISSUE #289: BUG: restore(clear=False) reflections added to other samples
```py
In [61]: config.restore(pathlib.Path("fourc-config.json"), clear=True)

In [62]: list_reflections(True)
Sample: main

 #   H  K  L   Two Theta    Theta      Chi      Phi   orienting   
 0   2  0  0      37.000    0.000   90.000   71.500   first        
 1   0  4  0      60.000   30.000   90.000    0.000   second       
============================================================================
Sample: EuAl4

 #   H  K  L   Two Theta    Theta      Chi      Phi   orienting   
 0   0  4  0      60.000   30.000   90.000    0.000   first        
 1   2  0  0      37.000    0.000   90.000   71.500   second       
============================================================================

In [63]: config.restore(pathlib.Path("fourc-config.json"), clear=False)

In [64]: list_reflections(True)
Sample: main

 #   H  K  L   Two Theta    Theta      Chi      Phi   orienting   
 0   2  0  0      37.000    0.000   90.000   71.500   first        
 1   0  4  0      60.000   30.000   90.000    0.000   second       
============================================================================
Sample: EuAl4

 #   H  K  L   Two Theta    Theta      Chi      Phi   orienting   
 0   0  4  0      60.000   30.000   90.000    0.000 
 1   2  0  0      37.000    0.000   90.000   71.500 
 2   2  0  0      37.000    0.000   90.000   71.500 
 3   0  4  0      60.000   30.000   90.000    0.000 
 4   0  4  0      60.000   30.000   90.000    0.000   first        
 5   2  0  0      37.000    0.000   90.000   71.500   second       
============================================================================
```

It looks like when `clear=False`, it reads reflections from 'main' also into the following sample.

_Originally posted by @strempfer in https://github.com/bluesky/hklpy/issues/279#issuecomment-1798543499_

### PR DESCRIPTION
**Pull request by prjemian**
- close #289

### CODE REVIEW

**Comment by prjemian** [comment]
@strempfer, see if this branch resolves the problem you reported

**Comment by prjemian** [comment]
@padraic-shafer : Hope that [94fef13](https://github.com/bluesky/hklpy/pull/292/commits/94fef13181c17584ab49e4b49496fb3c931e3fdf) is what you had in mind.

@mrakitin This is ready for review.  @strempfer has been requested to test it (since it was he who reported the problem).

**Comment by prjemian** [comment]
off line conversation with @strempfer:

[9:15 PM] Strempfer, Joerg
... It looks like everything is read correctly when using the overwrite option (`clear=True`). But when using `clear=False`, it is also replacing everything and is not appending.

[9:18 PM] Jemian, Pete R.
Can you send me a copy of the config file you are restoring AND also make an export of the diffractometer just before you do the restore?  That will help me to track this down.
[9:18 PM] Jemian, Pete R.
I expect the two files will not be identical. Right?

[9:32 PM] Strempfer, Joerg
sorry, I was just re-reading the file and expected the reflections to append, as was the case before, but which I think was already the bug.  Now it is replacing only reflections which are identical and already there before the sate was saved when doing `clear=False` but leaved new reflections there as well.
So, everything seems fine. I cannot test this further right now, since the IOC for the soft motors on elevate somehow doesn't start anymore.

[9:34 PM] Jemian, Pete R.
Right.  It replaces a reflection that matches hkl & wavelength (each to 7 digits).  Assumes that restore means replace existing reflection with values from the file.  Is this the right behavior?  (We really should put this discussion in the github PR for others to see.)

[9:46 PM] Strempfer, Joerg
This is actually not what I expected. There might be identical reflections with different angular values, e.g. if the lattice parameter changes with temperature. Right now it restores only the orienting reflections but I think we need to restore all reflections.
 
```py
In [18]: list_reflections(True)
Sample: main
#   H  K  L    Delta    Theta      Chi      Phi    Gamma       Mu   orienting   
0   0  0  2   40.000   20.000   16.690   10.000    9.230    0.000
1   0  4  0   60.000   30.000    0.000    0.000    0.000    0.000   second       
2   0  0  2   40.000   21.000   16.690   10.000    9.230    0.000   first        
============================================================================
Sample: EuAl4
 
#   H  K  L    Delta    Theta      Chi      Phi    Gamma       Mu   orienting   
0   0  0  2   40.000   21.000   16.690   10.000    9.230    0.000
1   0  4  0   60.000   30.000    0.000    0.000    0.000    0.000   second       
2   0  0  2   40.000   22.000   16.690   10.000    9.230    0.000
3   0  0  2   40.000   22.000   16.690   10.000    9.230    0.000   first        
============================================================================

In [19]: write_config()
Overwrite existing configuration file (y/[n])? y
Writing configuration file.
 
In [20]: read_config()
Read configuration file 'diffract-config.json'.
Method ([o]verwrite/[a]ppend)? o
 
In [21]: list_reflections(True)
Sample: main
 
#   H  K  L    Delta    Theta      Chi      Phi    Gamma       Mu   orienting   
0   0  4  0   60.000   30.000    0.000    0.000    0.000    0.000   first        
1   0  0  2   40.000   21.000   16.690   10.000    9.230    0.000   second       
============================================================================
Sample: EuAl4
 
#   H  K  L    Delta    Theta      Chi      Phi    Gamma       Mu   orienting   
0   0  4  0   60.000   30.000    0.000    0.000    0.000    0.000   first        
1   0  0  2   40.000   22.000   16.690   10.000    9.230    0.000   second       
============================================================================
```

I just see it restores also other reflections than the orienting ones but only one of a kind.

**Comment by prjemian** [comment]
Since there is no `update_reflection()` code available (hint for v2 feature), the restore procedure removes a matching reflection before adding it (as a new reflection).  Avoids duplicating a reflection.
https://github.com/bluesky/hklpy/blob/bf8e0bb800f52c70886262b2eb1853f59e6ed9f4/hkl/configuration.py#L298-L300

**Comment by prjemian** [comment]
Under what circumstances would the same hkl & wavelength be used with different angles?  You said for different sample temperatures?  How could you use these to compute a UB matrix?  They have different lattice spacings.  That changes the UB matrix.

**Review by padraic-shafer — APPROVED** [review]
Re: `__init__` --> `tools`, I'm honored. :)

The tests look good too (via visual inspection...unable to install libhkl on macos).

**Comment by padraic-shafer** [comment]
> Under what circumstances would the same hkl & wavelength be used with different angles? You said for different sample temperatures? How could you use these to compute a UB matrix? They have different lattice spacings. That changes the UB matrix.

In practice, it's very common to not change the stored lattice basis for a sample during an experiment, but instead to encode the lattice expansion/contraction as "changes" in (_hkl_) values of an observed reflection.  Alternatively some beamline conventions keep (_hkl_) of the reflection fixed, and "absorb" the lattice changes by allowing the diffraction angles for that reflection to vary.

You're right that updating the lattice parameters would be the proper physical property to track, but this is usually a buried configuration in scan software that does not get logged and which might involve "resetting" the system.  So tracking changes in (_hkl_) or diffraction angles is a common coping mechanism to keep an experiment running.

I won't speak for @strempfer here, but wanted to share that this is a fairly common practical approach.

**Comment by strempfer** [comment]
Reflections are always saved with integer hkl but more or less different angles. So right now only the last added reflection (I hope) is restored. Usually this is sufficient but what about a flag allowing to restore all reflections?

**Comment by prjemian** [comment]
It's easy to make a change here.  Let me be clear on what is to be done.  In this code, an identical reflection is found by matching both wavelength and hkl to some numerical precision.  https://github.com/bluesky/hklpy/blob/bf8e0bb800f52c70886262b2eb1853f59e6ed9f4/hkl/configuration.py#L227-L232

I'm trying to avoid the situation where `restore(clear=False)` increases the number of reflections by appending the same reflections to the existing ones.

Both of you are saying it is common practice to have multiple reflections that satisfy this match.  The change would also compare the angles.  If wavelength, hkl, and angles all match to some numerical precision, then it is the same reflection, right?

**Comment by padraic-shafer** [comment]
> Both of you are saying it is common practice to have multiple reflections that satisfy this match. The change would also compare the angles. If wavelength, hkl, and angles all match to some numerical precision, then it is the same reflection, right?

_Just thinking aloud here..._

I think this approach will bump into troubles because "to some numerical precision" will depend very much on the sample and experiment, and retrieving multiple matches might not add much value without additional context.

Another approach might be to allow additional key:value pairs to be stored with the sample/reflection...such as temperature.  When restoring, the calling user could specify additional keys (`..., temperature=sample.temperature`) to use for matching the stored reflection.  This might add more complexity than you want to handle in this way, so you know, feel free to shoot this down. :)

**Comment by prjemian** [comment]
How about a label for reach reflection? The user could put that metadata in
the label. It the label could be autogenerated if the user did not
provide.  A label would make it much easier to prevent the addition of
additional copies of the same reflection.

**Comment by padraic-shafer** [comment]
> How about a label for reach reflection? The user could put that metadata in the label. It the label could be autogenerated if the user did not provide. A label would make it much easier to prevent the addition of additional copies of the same reflection.

I like that very much.

**Comment by strempfer** [comment]
Wouldn't it be best to just append all reflections without checking? This is what I would expect for a `clear=False`. There is the possibility for the user to delete unwanted reflections afterwards.

**Comment by strempfer** [comment]
A label would still be great.

**Comment by prjemian** [comment]
This is easy for the programmer, given the way that reflections now are
stored in the back end library. Seems messy for the user.

We can save the label idea for v2 where things like this are designed in,
not added as an afterthought.

**Comment by prjemian** [comment]
With reflection levels, the config file format would have to change.
Reflections would be a dictionary rather than a list. Because of that, is
love to do this as soon as possible.  In this branch.

**Comment by prjemian** [comment]
> Reflections are always saved with integer hkl but more or less different angles. So right now only the last added reflection (I hope) is restored. Usually this is sufficient but what about a flag allowing to restore all reflections?

For crystallographers, hkl are Miller indices and are always integers.  In practice, some use a _reflection_ as a fiducial marker to note a setting of reciprocal and real-space positions.  In such case, thinking diffues scattering as the example, hkl could be non-integer.  It's more general to keep as a float.

**Comment by prjemian** [comment]
Let's implement reflection labels in a branch from this one.

**Comment by prjemian** [comment]
There are several use cases for a set of reflections:

- computation of the orientation matrix (for 2 or more reflections)
- documentation of observed (or theoretical) reflection settings
- reference coordinates to re-position the diffractometer (move to this one)
- define a crystallographic zone or axis to guide the diffractometer for measurements

**Comment by prjemian** [comment]
While reflection labels sound like a way to recognize identical reflections, their addition will touch many modules and could introduce breaking changes.  Breaking changes are beyond the intent of this PR.  The plans for v2 include such breaking changes.

Summary: Not going to add reflection labels now.  Instead, when `clear=False`, then will blindly append reflections from config to existing set.  That is easy and will not represent a departure from what users know how to do now.

**Comment by prjemian** [comment]
@strempfer:  I have pushed the latest changes now.  Can you `git pull` in your branch and test again?

**Comment by strempfer** [comment]
Looks good. Don't see any problems. Thanks!

**Comment by strempfer** [comment]
Actually, what did you modify? Does it look at the different angles now? It looks like in both overwrite and append mode, it only reads one reflection of a kind even that angles are different.

**Review by klauer — APPROVED** [review]

**Comment by strempfer** [comment]
Did a git pull again and now it works as it should.

**Review by strempfer — APPROVED** [review]

**Review by mrakitin — APPROVED** [review]
The changes make sense to me and the test coverage is good.

**Pull request merged**
