### PR TITLE
MNT #139 new graphic, with labels!

### LINKED ISSUE #139: Switch the E6C graphic to 4S+2D

### PR DESCRIPTION
**Pull request by prjemian**
In discussion at APS, @jwkim-anl noted the existing graphic for the 6-circle example is not right for the E6C geometry implemented in [hkl](https://people.debian.org/~picca/hkl/hkl.html#orge5e0490).  This will fix #139 with a labeled version of the existing 4S+2D graphic.

Here's a view of that.
Comments? @jwkim-anl, @ambarb, @strempfer, @cmazzoli, @crl3, @gfabbris
4S+2D-labeled

### CODE REVIEW

**Comment by prjemian** [comment]
@stuwilkins: comments?

**Comment by ambarb** [comment]
@prjemian can we look at the source code and build what the source code says?  I don't know where to find the c-code to read.  Can someone share it?  

I think there is a lot of confusion in trying to understand which six circle is meant by E6C so maybe we can get to the bottom of that. For my benefit (and anyone else that wants to jump in)

spec's sixc and psic are for two different diffractometers
# [spec's sixc](https://certif.com/spec_help/sixc.html`) 
- six-circle diffractometer were presented by M. Lohmeier and E. Vlieg in J. Appl. Cryst., 26, 706 (1993) [paper here](https://onlinelibrary.wiley.com/doi/abs/10.1107/S0021889893004868) or [try this scripts link](http://scripts.iucr.org/cgi-bin/paper?S0021889893004868)
- this figure looks like it was designed to match spec's sixc motor names [research gate equivalent figure](https://www.researchgate.net/figure/a-Schematic-diagram-of-a-six-circle-diffractometer-showing-the-six-rotation-circles_fig10_279829439) 
Screen Shot 2021-04-29 at 6 55 19 PM


- there are two degrees of freedom for the detector -  stacked on top of each other directly with orthongonal 
    - the "vertical" axis of rotation is outer most
    - the "horizontal" axis of rotation is inner most 
- inner most detector rotation ("horizontal") has another motor that rotates in the same way, but it is the outer most rotation of the ENTIRE diffractometer.


# [spec's psic](https://certif.com/spec_help/psic.html)
-  the psi-circle diffractometer are based on those presented in a paper by H. You of Argonne National Lab in J. Appl. Cryst., 32, 614-623 (1999). [paper here](https://journals.iucr.org/j/issues/1999/04/00/hn0093/)
- the figure you have here, looks like a 4+2 diffractometer and matches what Hoydoo has in his paper but with names from E6C.

**Comment by prjemian** [comment]
The graphic is directly from the hkl documentation source code. A link to
the hkl source code is in the hklpy project home page and also in the index
page of the documentation.  This *is* the e6c drawing from Picca. Today, I
marked the axis names in hopes to clarify.  As it turns out, the APS has
many such 6-circles, not many with the design with gamma riding on the
delta axis.

**Comment by prjemian** [comment]
In *hkl*'s source code (https://repo.or.cz/hkl.git), file `hkl/hkl-engine-e6c.c`, at line 359:

```c
static HklGeometry *hkl_geometry_new_eulerian6C(const HklFactory *factory)
{
	HklGeometry *self = hkl_geometry_new(factory, &hkl_geometry_operations_defaults);
	HklHolder *h;

	h = hkl_geometry_add_holder(self);
	hkl_holder_add_rotation(h, MU, 0, 0, 1, &hkl_unit_angle_deg);
	hkl_holder_add_rotation(h, OMEGA, 0, -1, 0, &hkl_unit_angle_deg);
	hkl_holder_add_rotation(h, CHI, 1, 0, 0, &hkl_unit_angle_deg);
	hkl_holder_add_rotation(h, PHI, 0, -1, 0, &hkl_unit_angle_deg);

	h = hkl_geometry_add_holder(self);
	hkl_holder_add_rotation(h, GAMMA, 0, 0, 1, &hkl_unit_angle_deg);
	hkl_holder_add_rotation(h, DELTA, 0, -1, 0, &hkl_unit_angle_deg);

	return self;
}
```

This is grouped as a 4S+2D geometry.

**Comment by ambarb** [comment]
Awesome.  I got some snippets of the source code from someone else, but it didn't have what you share.  I wonder if it is even the same version.   What version are you using?   @mrakitin how can we tell which version of the pica was used to build the library.  I just want to make absolutely sure we are all on the same page.

But Yes, definitely it looks to be the case  of 4+2, as the other 6-circle would have to define that diffractometer's mu separately since it moves both the sample and the detectors.

**Comment by mrakitin** [comment]
> Awesome. I got some snippets of the source code from someone else, but it didn't have what you share. I wonder if it is even the same version. What version are you using? @mrakitin how can we tell which version of the pica was used to build the library. I just want to make absolutely sure we are all on the same page.

@ambarb, we technically do not build an extension to the `hkl` library, as there is no C/C++ extension used in
https://github.com/bluesky/hklpy/blob/dc4abd69d01287ad7528272998738600bd26503f/setup.py#L6-L15

The `hkl` C++ library us used via `gi` (gobject-introspection/pygobject).

The relevant feedstocks are:
- https://github.com/nsls-ii-forge/hkl-feedstock
- https://github.com/nsls-ii-forge/hklpy-feedstock

We use the GitHub source of `hkl`, that hasn't been updated for a while. The version used is [`5.0.0.2173`](https://github.com/nsls-ii-forge/hkl-feedstock/blob/10d7ce4eca5437828960eb926382b2888c59b814/recipe/meta.yaml#L2) from https://github.com/picca/hkl/releases/tag/v5.0.0.2173 (that is "just" 5 years old).

The `hklpy` conda package uses `hkl` as a [run dependency](https://github.com/nsls-ii-forge/hklpy-feedstock/blob/0e8291e3fb992bfea9b68027a5083f8311000bf0/recipe/meta.yaml#L24).

Does it answer your questions?

**Comment by ambarb** [comment]
Yes @mrakitin that is great. 

I need to research on how to see this hkl dependency from the python interface unless you know for sure this not possible and the only way to know it to go digging in the links your provided.

**Comment by prjemian** [comment]
@ambarb : The *conda* tool can show what version is packaged for use now:

```sh
(bluesky_2021_1) mintadmin@mint-vm:~$ conda list hkl
# packages in environment at /home/mintadmin/Apps/anaconda/envs/bluesky_2021_1:
#
# Name                    Version                   Build  Channel
hkl                       5.0.0.2173       py38h7fad713_1    conda-forge
hklpy                     0.3.14+251.gca2ca51           dev_0    <develop>
```

We're using 5.0.0.2173.  The most recent [tag](https://repo.or.cz/hkl.git/refs), 7 months ago, is v5.0.0.2661.

**Comment by prjemian** [comment]
BTW: 2173 is 4 years ago.

**Comment by prjemian** [comment]
@ambarb, @mrakitin This is ready for review.

**Comment by prjemian** [comment]
Have not (yet) found a way to get [that build number](https://github.com/bluesky/hklpy/pull/146#issuecomment-840932069) from Python.  Want to include it in #160.

**Comment by gfabbris** [comment]
Looks good 👍🏼

**Comment by ambarb** [comment]
Looks good to me.  Thanks for you patience and questions. Learned a lot.  I didn't realize that the c code got packaged with `hkl` so that is great to learn as well.
👍

**Review by ambarb — APPROVED** [review]

**Review by mrakitin — APPROVED** [review]
Looks good to me from the code perspective, Pete! The domain experts commented on the geometry itself.

**Comment by prjemian** [comment]
@mrakitin : Thanks for the review!

**Pull request merged**
