### PR TITLE
repair CI

### LINKED ISSUE #193: CI is failing
With recent merges, the CI is now failing (where it did not fail in the PR's branch).

One fail, in the [Py3.8 build](https://github.com/bluesky/hklpy/runs/3192758925?check_suite_focus=true), is due to missing `pandoc` package.  This fail blocks building of the documentation.

```sh
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbconvert/utils/pandoc.py", line 77, in get_pandoc_version
    raise PandocMissing()
nbconvert.utils.pandoc.PandocMissing: Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
```

Another failure, in the [Py3.6 build](https://github.com/bluesky/hklpy/runs/3188404665?check_suite_focus=true), is due to a problem with the `xarray` package.

```sh
/usr/share/miniconda/envs/test-hklpy/lib/python3.6/site-packages/xarray/core/dataarray.py:24: in <module>
    from . import (
E     File "/usr/share/miniconda/envs/test-hklpy/lib/python3.6/site-packages/xarray/core/computation.py", line 4
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
```

### PR DESCRIPTION
**Pull request by prjemian**
FIX #193 

Drop support for Python 3.6

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin This is ready for review.

**Review by mrakitin — APPROVED** [review]
👍 Looks good to me!

**Comment by prjemian** [comment]
Thanks!  Rapid cycle on this one!  Group discussion today was helpful.

**Comment by prjemian** [comment]
BTW, working this through in a local Docker container (initially some setup work) made this much faster to discover the real problems and resolve them quickly.  Highly recommend that technique.

**Pull request merged**
