### PR TITLE
additions from apstools

### LINKED ISSUE #78: add DiffractometerMixin from apstools
The [apstools](https://github.com/BCDA-APS/apstools) package has a supplementary diffractometer support, including a [`DiffractometerMixin`](https://github.com/BCDA-APS/apstools/blob/6433db2451d9dae994fd9e3663663f7f5082b0c6/apstools/diffractometer.py#L55) class.  All of this would be a strong addition to the *hklpy* package.

In *apstools*, there are open issues to resolve here:

* [x] [diffractometer wh report should use defined energy units](https://github.com/BCDA-APS/apstools/issues/469)
* [x] [unit tests of diffractometer support](https://github.com/BCDA-APS/apstools/issues/309)

Also, add the Constraint support.

### LINKED ISSUE #86: BUG: changed energy units, got same energy value
When developing unit tests for new `hkl.diffract.Diffractometer.wh()` method (#78) discovered that reported energy value did not change when the units were changed from `keV` to `eV`.

```python
def test_change_energy_units(fourc):
    assert fourc.energy.get() == 8
    assert fourc.energy_units.get() == "keV"
    fourc.energy_units.put("eV")
    assert fourc.energy.get() == 8000
```

results in a test failure:

```
========================================================= FAILURES =========================================================
_________________________________________________ test_change_energy_units _________________________________________________

fourc = Fourc(prefix='', name='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['h...ck', 'l.setpoint', 'omega', 'chi', 'phi', 'tth'], configuration_attrs=['energy', 'UB', 'h', 'k', 'l'], concurrent=True)

    def test_change_energy_units(fourc):
        assert fourc.energy.get() == 8
        assert fourc.energy_units.get() == "keV"
        fourc.energy_units.put("eV")
>       assert fourc.energy.get() == 8000
E       assert 8.0 == 8000
E         +8.0
E         -8000

hkl/tests/test_diffract.py:171: AssertionError
================================================= short test summary info ==================================================
FAILED hkl/tests/test_diffract.py::test_change_energy_units - assert 8.0 == 8000
=============================================== 1 failed, 6 passed in 1.96s ================================================
```

### LINKED ISSUE #88: Add components for geometry and class name to Diffractometer
Also, *must* include the geometry description as part of the configuration information.  Use `SignalRO`.  Absolutely must.

_Originally posted by @prjemian in https://github.com/bluesky/hklpy/issues/50#issuecomment-751409649_

### PR DESCRIPTION
**Pull request by prjemian**
Add reports from the apstools DiffractometerMixin directly to the Diffractometer class.

Fix #78 

Also, fix #86 where Diffractometer.energy did not respond to changes to energy units and/or offset.

Also add Components for geometry_name and class_name (fix #88) so they are recorded with data to enable recovery of UB (#50) from previous runs and resume scanning.

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin Ready for review now.

**Comment by prjemian** [comment]
The new code here will support #63.  Simpler examples can be the result.

**Comment by mrakitin** [comment]
I am seeing additions from other, earlier PRs. Probably it would make sense to merge them first, then rebase this PR on `main` to eliminate the overlapping commits.

**Comment by prjemian** [comment]
The goal here was to bring in the user interface first worked out in *apstools* (#78).  While doing that, two other issues (#86 and #88) were exposed.  All these relate back to #50.  This is a set of issues that work together.  This PR lays foundation for the final work on #50 (to be completed after this PR is merged).

**Comment by mrakitin** [comment]
Ready to review it once the conflicts are resolved (by `git rebase main`).

The following _merge_ commit may not be the best solution to eliminate the overlapping commits:

image

I normally rebase.

**Comment by prjemian** [comment]
@mrakitin Thanks for the suggestions.  Evidence is building for a restart on this effort, taking it in pieces (multiple issues, merge conflicts, other PRs that could affect).  I'll look at new branches+PRs for the separate issues.

Not closing here.  Not yet.

**Review by mrakitin — APPROVED** [review]
I have no objections to merge it.

**Comment by mrakitin** [comment]
Oh, please disregard my approval, as #116 replaces this PR. Can we close this PR without merging then?

**Comment by prjemian** [comment]
And, PR #116 was just merged.

**Pull request closed without merging**
