### PR TITLE
Describe Diffractometers in tables

### LINKED ISSUE #155: table showing geometry, engines, modes, axes
Need a reference table of the available diffractometer geometries, calculation engines, pseudo & real axes, operating modes, and additional parameters.

### LINKED ISSUE #166: SOLEIL SIXS: geometry does not exist in libhkl
The `SOLEIL SIXS` geometry is not described by [*libhkl* source code](https://repo.or.cz/hkl.git/tree/HEAD:/hkl):

```sh
(base) mintadmin@mint-vm:~/.../hkl/hkl$ git grep SIXS
api2/hkl2.c:    case GEOMETRY_SOLEIL_SIXS_MED_2_3:
api2/hkl2.c:            self = hkl_factory_get_by_name("SOLEIL SIXS MED2+3", NULL);
api2/hkl2.c:    case GEOMETRY_SOLEIL_SIXS_MED_2_3_v2:
api2/hkl2.c:            self = hkl_factory_get_by_name("SOLEIL SIXS MED2+3 v2", NULL);
api2/hkl2.c:    case GEOMETRY_SOLEIL_SIXS_MED_2_3: NEW_GEOMETRY(soleil_sixs_med_2_3); break;
api2/hkl2.c:    case GEOMETRY_SOLEIL_SIXS_MED_2_3_v2: NEW_GEOMETRY(soleil_sixs_med_2_3_v2); break;
api2/hkl2.h:    GEOMETRY_SOLEIL_SIXS_MED_2_3,
api2/hkl2.h:    GEOMETRY_SOLEIL_SIXS_MED_2_3_v2,
api2/hkl2.h:    {.tag=GEOMETRY_SOLEIL_SIXS_MED_2_3,                             \
api2/hkl2.h:    {.tag=GEOMETRY_SOLEIL_SIXS_MED_2_3_v2,                          \
hkl-engine-soleil-sixs-med.c:/* SOLEIL SIXS MED 2+2 */
hkl-engine-soleil-sixs-med.c:#define HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_2_DESCRIPTION          \
hkl-engine-soleil-sixs-med.c:REGISTER_DIFFRACTOMETER(soleil_sixs_med_2_2,"SOLEIL SIXS MED2+2", HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_2_DESCRIPTION);
hkl-engine-soleil-sixs-med.c:/* SOLEIL SIXS MED 1+2 */
hkl-engine-soleil-sixs-med.c:#define HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_1_2_DESCRIPTION          \
hkl-engine-soleil-sixs-med.c:REGISTER_DIFFRACTOMETER(soleil_sixs_med_1_2, "SOLEIL SIXS MED1+2", HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_1_2_DESCRIPTION);
hkl-engine-soleil-sixs-med.c:/* SOLEIL SIXS MED 2+3 */
hkl-engine-soleil-sixs-med.c:#define HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_3_DESCRIPTION          \
hkl-engine-soleil-sixs-med.c:REGISTER_DIFFRACTOMETER(soleil_sixs_med_2_3, "SOLEIL SIXS MED2+3", HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_3_DESCRIPTION);
hkl-engine-soleil-sixs-med.c:/* SOLEIL SIXS MED 2+3 v2 */
hkl-engine-soleil-sixs-med.c:#define HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_3_V2_DESCRIPTION               \
hkl-engine-soleil-sixs-med.c:REGISTER_DIFFRACTOMETER(soleil_sixs_med_2_3_v2, "SOLEIL SIXS MED2+3 v2", HKL_GEOMETRY_TYPE_SOLEIL_SIXS_MED_2_3_V2_DESCRIPTION);
```

Remove `hkl.calc.CalcSoleilSixs` and `hkl.geometries.SoleilSixs`

### LINKED ISSUE #167: TwoC: drop this geometry for now
I recommend we drop `TwoC` geometry for now.  The libhkl library defines no engines for this geometry.  It will take some refactoring of `CalcRecip` to get around this one geometry.  I'd recommend the upstream *libhkl* be changed instead, to add a `q` engine, since that is the *only* one that makes any sense: q = (4pi/lambda)*sin(tth/2) -- *hkl* makes no sense for `TwoC` and that ruins the `engine="hkl"` default in `CalcRecip.__init__()`.  Still, `TwoC` will need a special case.

_Originally posted by @prjemian in https://github.com/bluesky/hklpy/issues/165#issuecomment-843313101_

### PR DESCRIPTION
**Pull request by prjemian**
FIX #155, FIX #166, FIX #167

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin This is ready to review.  I built the tables using Python code in the notebook (added to `docs/source/_static`).  Could there be a better place to retain this code?

**Comment by prjemian** [comment]
@jwkim-anl, @gfabbris, @strempfer, @rodolakis: Can you comment on this pull request please?

This pull request is an addition to the documentation.  It lists the axes, calculation engines (hkl, q, psi, incidence, ...) , modes, and any additional parameters for each of the available diffractometer geometries.  The documentation is (mostly formatted, some markup still visible here) in file: https://github.com/bluesky/hklpy/blob/e78cde4b854b1613716dafe13c19e4ea8f21440f/docs/source/geometry_tables.rst

**Review by rodolakis — APPROVED** [review]

**Comment by prjemian** [comment]
Thanks @rodolakis!

**Review by mrakitin — APPROVED** [review]
Looks good to me! That's very valuable tabular information. Thanks, @prjemian!

**Comment by prjemian** [comment]
@mrakitin Thanks!  I've asked some folks at APS to review as well.  I'll wait for them until tomorrow.

**Comment by strempfer** [comment]
Looks good!

**Comment by prjemian** [comment]
@strempfer : Thanks for the review!

**Review by jwkim-anl — APPROVED** [review]
Looks great - very well organized tables.

**Review by strempfer — APPROVED** [review]

**Comment by prjemian** [comment]
@jwkim-anl - Thanks for the review!

**Review by gfabbris — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
@gfabbris Thanks for the review!  That's all of us so now proceeding to merge.

**Pull request merged**
