### PR TITLE
Create simulators for common geometries

### LINKED ISSUE #98: in tests, copy `Fourc` class to separate file for import
In the unit tests, the `Fourc()` class is used repeatedly.  Copy this into a separate file for `from .fourc_class import Fourc` or such.  Also, can the `fourc` fixture be imported from this separate file as well?

### PR DESCRIPTION
**Pull request by prjemian**
FIX #98

### CODE REVIEW

**Comment by prjemian** [comment]
Ready for review

**Comment by prjemian** [comment]
@mrakitin - This is ready for review.

**Review by mrakitin — APPROVED** [review]
💯 on the DRY principle!

**Comment by prjemian** [comment]
Thanks! Had to look up DRY principle. Yes, that's it!

**Comment by mrakitin** [comment]
Yes, "Don't Repeat Yourself" 👍

**Pull request merged**
