### PR TITLE
move on from py37 and previous

### LINKED ISSUE #328: Move on from pre-Py3.7 code
Such as https://github.com/bluesky/hklpy/blob/a44d0db3fcfb3e3f43122f420947192e58b23c12/hkl/util.py#L579-L585

### PR DESCRIPTION
**Pull request by prjemian**
- close #328

### CODE REVIEW

**Review by padraic-shafer — COMMENTED** [review]
The "tool list" change looks reasonable.

What is the context for "tmate" and its removal?

**Comment by prjemian** [comment]
tmate would be used for interactive debugging within a GHA workflow.  Has not been used in some years and is likely bit-rot.  Should we ever want todo such things again, better to start from scratch.  The [nektos-act](https://github.com/nektos/act) action, that runs workflows locally, is a better choice.

**Comment by mrakitin** [comment]
> tmate would be used for interactive debugging within a GHA workflow. Has not been used in some years and is likely bit-rot. Should we ever want todo such things again, better to start from scratch. The [nektos-act](https://github.com/nektos/act) action, that runs workflows locally, is a better choice.

BNL blocks [tmate](https://tmate.io/). It's fine to remove it.

+1 for the `act` - I used it for a couple of repos and it looks good.

**Review by mrakitin — APPROVED** [review]
The changes look good to me!

**Comment by prjemian** [comment]
@padraic-shafer , @mrakitin - Thanks!

**Pull request merged**
