### PR TITLE
Declare SI_LATTICE_PARAMETER & SI_LATTICE_PARAMETER_UNCERTAINTY constants

### LINKED ISSUE #156: Si lattice constant: higher precision
In various places, the lattice constant of silicon is used as 5.4310196 Angstrom.  The 2018 CODATA recommended lattice parameter of silicon ([NIST source](https://physics.nist.gov/cgi-bin/cuu/Value?asil)) is:

term | value
--- | ---
Numerical value |	 5.431 020 511 x 10-10 m
Standard uncertainty |	 0.000 000 089 x 10-10 m
Relative standard uncertainty |	 1.6 x 10-8
Concise form |	 5.431 020 511(89) x 10-10 m

### LINKED ISSUE #177: Correction to current wavelength and UB matrix calculation.
In the example notebooks, it is stated that:

> The `compute_UB()` method uses the current wavelength.

This is not correct.  The correct text should identify that the current wavelength is used when each reflection is added, via: `Diffractometer.calc.sample.add_reflection()`.  It is possible to calculate **UB** from two orientation reflections, each with a different wavelength.

This association is handled (now) by the *libhkl* support library.

### PR DESCRIPTION
**Pull request by prjemian**
FIX #156 and FIX #177

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin This is ready for review.

**Review by mrakitin — APPROVED** [review]
Everything looks good to me besides the spotted difference between the representations of the lattice constants:
- in https://github.com/bluesky/hklpy/blob/863a3055f68f77d635d2d260dd04b2fe3e6bb94c/examples/geo_e6c.ipynb, it displays:
```py
HklSample(name='silicon', lattice=LatticeTuple(a=5.431020511, b=5.431020511, c=5.431020511, alpha=90.0, beta=90.0, gamma=90.0), ux=Parameter(name='None (internally: ux)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), uy=Parameter(name='None (internally: uy)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), uz=Parameter(name='None (internally: uz)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), U=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), UB=array([[ 1.15690694e+00, -7.08401189e-17, -7.08401189e-17],
       [ 0.00000000e+00,  1.15690694e+00, -7.08401189e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.15690694e+00]]), reflections=[])
```
- however in https://github.com/bluesky/hklpy/blob/863a3055f68f77d635d2d260dd04b2fe3e6bb94c/examples/geo_k4cv.ipynb, the corresponding information is printed with the lower accuracy:
```py
HklSample(name='silicon', lattice=LatticeTuple(a=5.431, b=5.431, c=5.431, alpha=90.0, beta=90.0, gamma=90.0), ux=Parameter(name='None (internally: ux)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), uy=Parameter(name='None (internally: uy)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), uz=Parameter(name='None (internally: uz)', limits=(min=-180.0, max=180.0), value=0.0, fit=True, inverted=False, units='Degree'), U=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), UB=array([[ 1.15691131e+00, -7.08403864e-17, -7.08403864e-17],
       [ 0.00000000e+00,  1.15691131e+00, -7.08403864e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.15691131e+00]]), reflections=[])
```

Is it expected?

**Comment by prjemian** [comment]
@mrakitin : I'll re-run that notebook.

**Review by mrakitin — APPROVED** [review]
Looks good to me now 😀

**Comment by prjemian** [comment]
@mrakitin Thanks!

**Pull request merged**
