### PR TITLE
move CI from travis to Github Actions

### LINKED ISSUE #53: Switch the CI from travis to Github Actions
... whatever the other bluesky projects are using now.

* [x] setup CI process
* [x] build for all python versions ['3.6', '3.7', '3.8']
* [x] CI status: badging
* [x] drop travis-ci

### PR DESCRIPTION
**Pull request by prjemian**
fixes #53

### CODE REVIEW

**Comment by prjemian** [comment]
This is part of the trouble here:

```
Warning: The environment name on "environment-file" is not the same as "enviroment-activate", using "environment-file"!
/usr/share/miniconda/condabin/mamba env create --file environment.yml --name hklpy
```

**Comment by prjemian** [comment]
This one test fails on Github Actions, passes locally:

```
__________________ ERROR collecting test_extra_real_fatal.py ___________________
ImportError while importing test module '/tmp/pytest-of-runner/pytest-0/test_extra_real_fatal0/test_extra_real_fatal.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/share/miniconda/envs/hklpy-test-3.6/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_extra_real_fatal.py:6: in <module>
    from hkl.diffract import E4CV
E   ModuleNotFoundError: No module named 'hkl'
=========================== short test summary info ============================
ERROR test_extra_real_fatal.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.75s ===============================
=========================== short test summary info ============================
FAILED hkl/tests/test_extra_motor.py::test_extra_real_fatal - Failed: remains...
========================= 1 failed, 26 passed in 9.13s =========================
```

Very likely to be related to conda environment configuration.

How to make sure that such tests launch in the chosen conda environment?

**Comment by prjemian** [comment]
https://docs.pytest.org/en/stable/reference.html?highlight=runpytest_subprocess#pytest.pytester.Testdir.runpytest_subprocess

**Comment by prjemian** [comment]
https://docs.pytest.org/en/stable/reference.html?highlight=runpytest_subprocess#pytest.pytester.Testdir.runpytest_subprocess

**Comment by prjemian** [comment]
Wahoo, ready for revoo (er review)!

**Review by mrakitin — COMMENTED** [review]
Did not have a chance to address the review request earlier, but it looks good to me.

Why was the `tmate` config removed? Isn't it useful to keep it for debugging purposes?

**Comment by prjemian** [comment]
The `tmate.yml` was removed in general cleanup of code not currently in use.  It was a duplicate of the [Getting Started](https://github.com/marketplace/actions/debugging-with-tmate#getting-started) script.  Better to visit that page fresh when the desire to debug happens again.  The best recommendation might change.

**Comment by prjemian** [comment]
Ok, just a bit more custom for this project: https://github.com/bluesky/hklpy/blob/e572c19820325921d8142dc7a3bfbe407f07421c/.github/tmate.yml#L1-L26

**Comment by prjemian** [comment]
Line 23 is the real value here:

```bash
sed -i.bak "s/name: ${PACKAGE}/name: ${ENV_NAME}/g" environment.yml
```

**Comment by prjemian** [comment]
I'll restore this [yaml file](https://github.com/bluesky/hklpy/blob/e572c19820325921d8142dc7a3bfbe407f07421c/.github/tmate.yml#L1), but leave it _inactive_ by placing it in the `<root>/.github/` directory.

**Pull request merged**
