### PR TITLE
update example notebooks, move in hkl, rel_scan, use SimMixin

### LINKED ISSUE #65: Show the constraints in the geometry examples
In the notebook link, I don't see anywhere where the calculation limits are set so the values that are displayed may not even be possible to reach with a physical diffractometer.  The exercise seems just to be to show people that the coordinate system is correctly defined.

_Originally posted by @ambarb in https://github.com/bluesky/hklpy/issues/52#issuecomment-748196433_

### LINKED ISSUE #67: in geometry examples, show a move(hkl) & rel_scan near the (440)
For the (hk0) scan near the (440), do this with a move to (440), then `bp.rel_scan()`.  It's a common type of scan to demonstrate.

Do this for all existing geometry examples (`examples/geo_*.ipynb`).

### PR DESCRIPTION
**Pull request by prjemian**
fix #67 & fix #65

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin : The differences might be tedious to examine since these changes are all in Jupyter notebooks.  Might be easier to build examine the notebooks with Jupyter or build the documentation and look at the HTML.

**Comment by prjemian** [comment]
While we're at it, and since reviewing changes in notebooks is more involved, let's add #65 (show Constraints) to this PR.

**Comment by prjemian** [comment]
@mrakitin This is ready for review.

**Review by mrakitin — APPROVED** [review]
I generated the documentation/examples and looked through all of them. I did not spot any issues. I think it's OK to merge and get the examples updated online, and the follow-up fixes (if any) can be done via a separate PR.

**Comment by prjemian** [comment]
@mrakitin Thanks!!!  That's the last big issue for this release.  Next, the history of changes, and then an rc release process to test for problems before final tag as 0.3.16, right?

**Comment by mrakitin** [comment]
Sounds like a plan :)

**Pull request merged**
