### PR TITLE
preview a configuration before restoring

### LINKED ISSUE #288: ENH: preview samples that would be restored
@strempfer asks:

> [Could there] be a function like `restore_sample_list()`, which just lists the available samples in the respective file or PV. Otherwise one may not know which ones are available, especially if there are many different ones.

### PR DESCRIPTION
**Pull request by prjemian**
- close #288

Requested by @strempfer

### CODE REVIEW

**Review by mrakitin — COMMENTED** [review]
Thanks, @prjemian, nice addition. Do you mind adding a test or a usage example in the documentation/jupyter examples?

**Comment by prjemian** [comment]
@mrakitin @strempfer See the new HOWTO notebook in the documentation: https://github.com/bluesky/hklpy/blob/288-restore-preview/docs/source/examples/notebooks/how_configuration.ipynb

**Comment by prjemian** [comment]
@mrakitin Both documentation and tests have been added.  Ready for review.

**Review by mrakitin — APPROVED** [review]
Looks good to me! Thanks for your patience, @prjemian.

**Comment by prjemian** [comment]
@mrakitin Thanks!

**Pull request merged**
